const API_PREFIX = 
const IMAGE_HANDLER_ENDPOINT = 
const AWS_BUCKET_NAME = 
const MAILCHIMP_API_KEY = 
const MAILCHIMP_SERVER = 
const MAILCHIMP_BASE = 
const MAILCHIMP_FOLDER_ID =

    module.exports = {
        API_PREFIX,
        IMAGE_HANDLER_ENDPOINT,
        AWS_BUCKET_NAME,
        MAILCHIMP_API_KEY,
        MAILCHIMP_SERVER,
        MAILCHIMP_BASE,
        MAILCHIMP_FOLDER_ID
    }
